name: Release

on:
  push:
    tags:
      - 'v*'
    paths-ignore:
      - 'README.md'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - run: npm i -g vcloudblock-resource-cli@0.2.5

      - name: Pro-process resources
        run: |
          opt-size
          gen-config --version=${{ github.ref_name }}

      - name: Get version
        id: get-version
        run: |
          version=`echo ${{ github.ref_name }} | sed -r 's/[v]+//g'`
          echo ::set-output name=VERSION::$version

      - name: Zip resources
        uses: vimtor/action-zip@v1
        with:
            files: ./
            dest: external-resources-${{ steps.get-version.outputs.VERSION }}.zip

      - name: Checksum
        run: sha256sum external-resources-*.zip >> ${{ steps.get-version.outputs.VERSION }}-checksums-sha256.txt

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: VCloudBlock External Resources ${{ github.ref_name }}
          body: |
            ## Change Log (en)

            - **New feature**

                1. Feature 1.
                2. Feature 2.

            - **Fix bug**

                1. Bug 1.
                2. Bug 2.

            ## 更改日志 (zh-cn)

            - **新功能**

                1. 功能1。
                2. 功能2。

            - **修复错误**

                1. 错误1。
                2. 错误2。
          draft: true
          prerelease: false

      # Upload zip
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: external-resources-${{ steps.get-version.outputs.VERSION }}.zip
          asset_name: external-resources-${{ steps.get-version.outputs.VERSION }}.zip
          asset_content_type: application/zip

      # Upload checksum
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.get-version.outputs.VERSION }}-checksums-sha256.txt
          asset_name: ${{ steps.get-version.outputs.VERSION }}-checksums-sha256.txt
          asset_content_type: text/plain

      # Upload to digitalocean
      - name: Release resources to digital ocean spaces
        run: |
          export DO_KEY_ID=${{ secrets.DO_KEY_ID }}
          export DO_SECRET_KEY=${{ secrets.DO_SECRET_KEY }}
          upload-file --filePath=external-resources-${{ steps.get-version.outputs.VERSION }}.zip  --endPoint=https://sgp1.digitaloceanspaces.com --bucket=vcloudblock
          upload-file --filePath=${{ steps.get-version.outputs.VERSION }}-checksums-sha256.txt  --endPoint=https://sgp1.digitaloceanspaces.com --bucket=vcloudblock
